### ISSUE TITLE
Only generates factories for models with records

### ISSUE THREAD

**Issue by thetyrelcorporation** [markburns/to_factory#16]
Hey thanks first of all this gem is quite useful. I have a feature request if you have some time. Can their be an option to pass with ToFactory(include_empty_tables: true) or something to that effect that would generate all models based on their schema even if they have no records in the database. That way when its a fresh project with no data you can still get a nice stub for everything.

**Comment by markburns** [comment]
I think this should be handled by Rails generators shouldn't it? 

Here's how you set it up in case you weren't aware:
https://github.com/thoughtbot/factory_girl_rails#configuration

The reason for the existence of this project is when encountering older projects without tests, or projects where people didn't use factories. 

I'm not sure there is as much of a use case for new projects.

Closing because I don't see a strong case for it at the moment, but feel free to prove me wrong if there's something I've missed
